1-module/5-task
js-tasks-ru/jsbasic-20220811_sergey647 pull request #3
Opened 2022-08-11 09:18 UTC by BogdanovSergey

2022-08-11 09:21 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-08-11 11:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-08-12 12:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-08-12 14:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-08-13 07:16 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-13 07:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-08-15 15:24 UTC, koalex requested changes
Исправить **2-3**

2022-08-15 15:24 UTC, koalex commented on 2-module/3-task/index.js
> +    window.calculator.a = a;
Исправить на `this.a = a;`

2022-08-15 16:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-08-15 19:48 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-08-15 19:49 UTC, BogdanovSergey commented on 2-module/3-task/index.js
> +    window.calculator.a = a;
Спасибо, исправил!

2022-08-16 15:17 UTC, koalex approved these changes

2022-08-16 15:17 UTC, koalex commented on 3-module/1-task/index.js
> +    result.push(users[i].name);
Подразумевалось, что будет использован метод [map](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

2022-08-16 15:17 UTC, koalex commented on 3-module/5-task/index.js
> +    min: ready[0],
Есть методы [Math.max](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/max) и [Math.min](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/min)

2022-08-16 15:17 UTC, koalex commented on 4-module/3-task/index.js
> +      currentRow.setAttribute("hidden", "true");
Так лучше
`currentRow.hidden = true;`

2022-08-16 15:18 UTC, merged